<a href="https://colab.research.google.com/github/ManalSahafi/master-degree/blob/main/data_mining/FP_Growth_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install mlxtend

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: mlxtend in /usr/local/lib/python3.7/dist-packages (0.21.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from mlxtend) (57.4.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.2.0)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.21.6)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.3.5)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.7.3)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.0.2)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (3.2.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=3.0.0->mlxtend) (4.1.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.2->mlxtend) (2022.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=3.0.0->mlxtend) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=1.0.2->mlxtend) (3.1.0)

In [2]:
%pip install mlxtend --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: mlxtend in /usr/local/lib/python3.7/dist-packages (0.21.0)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.0.2)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.7.3)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from mlxtend) (57.4.0)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.3.5)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.21.6)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (3.2.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=3.0.0->mlxtend) (4.1.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.2->mlxtend) (2022.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=3.0.0->mlxtend) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=1.0.2->mlxtend) (3.1.0)

In [3]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns.fpgrowth import fpgrowth
from mlxtend.frequent_patterns import association_rules

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **Step1: Load the file text and convert as list of Transactions**

In [5]:
def Load_data(filename):
    with open(filename, "r") as infile:
            transactions = [set(line.rstrip("\n").split(";"))
                            for line in infile]

    return transactions

f = '/content/drive/MyDrive/Colab Notebooks/categories.txt'
transactions= Load_data(f)

#print the category text file
#transactions

# **Step2: Generate an encoded dataframe**

In [6]:
# instantiate a transaction encoder
transcoder = TransactionEncoder()

# fit the transaction encoder using the list of transaction tuples
transcoder.fit(transactions)

# transform the list of transaction tuples into an array of encoded transactions
transarray = transcoder.transform(transactions)

# convert the array of encoded transactions into a dataframe
trans_df = pd.DataFrame(transarray, columns = transcoder.columns_)
trans_df

,ATV Rentals/Tours,Accessories,Accountants,Active Life,Acupuncture,Adult,Adult Education,Adult Entertainment,Advertising,Afghan,...,Wigs,Window Washing,Windows Installation,Windshield Installation & Repair,Wine Bars,Wine Tasting Room,Wineries,Women's Clothing,Yelp Events,Yoga
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10798,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10799,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10800,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10801,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10802,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

# **Step3: Compute the frequent itemsets using fpgriowth from mlxtend**

In [7]:
min_support = 0.01
frequent_itemsets = fpgrowth(trans_df, min_support=min_support, use_colnames = True)

# print the frequent itemsets
frequent_itemsets

     support                                         itemsets
0   0.328520                                    (Restaurants)
1   0.029066                         (American (Traditional))
2   0.018884                             (Breakfast & Brunch)
3   0.032213                                     (Sandwiches)
4   0.043506                                 (Local Services)
..       ...                                              ...
95  0.010923         (Home Services, Apartments, Real Estate)
96  0.016107                     (Dentists, Health & Medical)
97  0.010553                    (Dentists, General Dentistry)
98  0.010553            (Health & Medical, General Dentistry)
99  0.010553  (Dentists, Health & Medical, General Dentistry)

[100 rows x 2 columns]

# **Step4: Compute the association rules based on the frequent itemsets**

In [8]:
# compute and print the association rules
association_rules(frequent_itemsets, metric="confidence", min_threshold=0.01)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(American (Traditional)),(Restaurants),0.029066,0.328520,0.029066,1.000000,3.043956,0.019517,inf
1,(Restaurants),(American (Traditional)),0.328520,0.029066,0.029066,0.088476,3.043956,0.019517,1.065176
2,(Breakfast & Brunch),(Restaurants),0.018884,0.328520,0.018884,1.000000,3.043956,0.012680,inf
3,(Restaurants),(Breakfast & Brunch),0.328520,0.018884,0.018884,0.057481,3.043956,0.012680,1.040951
4,(Sandwiches),(Restaurants),0.032213,0.328520,0.032213,1.000000,3.043956,0.021631,inf
...,...,...,...,...,...,...,...,...,...
117,"(Dentists, General Dentistry)",(Health & Medical),0.010553,0.066648,0.010553,1.000000,15.004167,0.009849,inf
118,"(Health & Medical, General Dentistry)",(Dentists),0.010553,0.016107,0.010553,1.000000,62.086207,0.010383,inf
119,(Dentists),"(Health & Medical, General Dentistry)",0.016107,0.010553,0.010553,0.655172,62.086207,0.010383,2.869397
120,(Health & Medical),"(Dentists, General Dentistry)",0.066648,0.010553,0.010553,0.158333,15.004167,0.009849,1.175581
121,(General Dentistry),"(Dentists, Health & Medical)",0.010553,0.016107,0.010553,1.000000,62.086207,0.010383,inf